import { Comic, Genre, Chapter, ChapterPage, Source, IngestLog, ReadingHistoryItem } from './types';

export const MOCK_GENRES: Genre[] = [
  { id: 1, name: 'Action', slug: 'action' },
  { id: 2, name: 'Adventure', slug: 'adventure' },
  { id: 3, name: 'Fantasy', slug: 'fantasy' },
  { id: 4, name: 'System', slug: 'system' },
  { id: 5, name: 'Romance', slug: 'romance' },
  { id: 6, name: 'Martial Arts', slug: 'martial-arts' },
  { id: 7, name: 'Isekai', slug: 'isekai' },
  { id: 8, name: 'Comedy', slug: 'comedy' },
  { id: 9, name: 'Drama', slug: 'drama' },
  { id: 10, name: 'Supernatural', slug: 'supernatural' },
];

export const MOCK_SOURCES: Source[] = [
  {
    id: 'src-1',
    name: 'Kiryuu Engine',
    base_url: 'https://kiryuu.id',
    scraping_config: { selector_title: 'h1.entry-title', selector_images: '.ts-main-image' },
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'src-2',
    name: 'Asura Scans ID',
    base_url: 'https://asuracomics.com',
    scraping_config: { selector_title: '.entry-title', selector_images: '#readerarea img' },
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const MOCK_COMICS: Comic[] = [
  {
    id: 'c-1',
    slug: 'solo-leveling',
    title: 'Solo Leveling',
    alt_titles: ['Na Honjaman Releveling', 'Only I Level Up'],
    type: 'manhwa',
    synopsis: '10 tahun yang lalu, setelah "Gerbang" yang menghubungkan dunia nyata dengan dunia monster terbuka, beberapa orang biasa mendapatkan kekuatan untuk berburu monster di dalam Gerbang. Mereka dikenal sebagai "Hunter". Sung Jin-Woo, seorang Hunter peringkat E terlemah, berjuang di dungeon paling berbahaya.',
    cover_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    author: 'Chugong / DUBU (REDICE STUDIO)',
    status: 'ongoing',
    rating: 4.95,
    source_id: 'src-1',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
    genres: [MOCK_GENRES[0], MOCK_GENRES[2], MOCK_GENRES[3]], // Action, Fantasy, System
    latest_chapter: {
      id: 'ch-101',
      chapter_number: 179,
      title: 'Kebangkitan Sang Shadow Monarch',
      released_at: new Date(Date.now() - 5 * 60000).toISOString(),
    },
  },
  {
    id: 'c-2',
    slug: 'one-piece',
    title: 'One Piece',
    alt_titles: ['Wan Pīsu'],
    type: 'manga',
    synopsis: 'Monkey D. Luffy menolak definisi bajak laut biasa. Alih-alih merampok dan menghancurkan, Luffy mencari petualangan menarik yang mempertemukannya dengan orang-orang hebat dan harta karun terbesar dunia, One Piece.',
    cover_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    author: 'Eiichiro Oda',
    status: 'ongoing',
    rating: 4.98,
    source_id: 'src-1',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60000).toISOString(),
    genres: [MOCK_GENRES[0], MOCK_GENRES[1], MOCK_GENRES[7]], // Action, Adventure, Comedy
    latest_chapter: {
      id: 'ch-201',
      chapter_number: 1115,
      title: 'Dunia yang Tenggelam',
      released_at: new Date(Date.now() - 12 * 60000).toISOString(),
    },
  },
  {
    id: 'c-3',
    slug: 'martial-peak',
    title: 'Martial Peak',
    alt_titles: ['Wu Lian Dian Feng'],
    type: 'manhua',
    synopsis: 'Perjalanan menuju puncak bela diri adalah perjalanan yang panjang, kesepian, dan penuh tantangan. Kai Yang, seorang murid penyapu di Paviliun Lingxiao, menemukan Kitab Hitam misterius yang mengubah takdirnya.',
    cover_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    author: 'Momo',
    status: 'ongoing',
    rating: 4.78,
    source_id: 'src-2',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60000).toISOString(),
    genres: [MOCK_GENRES[0], MOCK_GENRES[5]], // Action, Martial Arts
    latest_chapter: {
      id: 'ch-301',
      chapter_number: 3520,
      title: 'Terobosan Ranah Kaisar',
      released_at: new Date(Date.now() - 30 * 60000).toISOString(),
    },
  },
  {
    id: 'c-4',
    slug: 'tower-of-god',
    title: 'Tower of God',
    alt_titles: ['Sin-ui Tap'],
    type: 'manhwa',
    synopsis: 'Apa yang kamu inginkan? Kekayaan? Kehormatan? Wewenang? Kekuatan? Balas dendam? Atau sesuatu yang melampaui itu semua? Apapun yang kamu cari, ada di puncak Menara.',
    cover_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    author: 'SIU',
    status: 'ongoing',
    rating: 4.85,
    source_id: 'src-2',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    genres: [MOCK_GENRES[0], MOCK_GENRES[2]], // Action, Fantasy
    latest_chapter: {
      id: 'ch-401',
      chapter_number: 600,
      title: 'Kebenaran di Lantai 135',
      released_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
  },
  {
    id: 'c-5',
    slug: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    alt_titles: ['Sorcery Fight'],
    type: 'manga',
    synopsis: 'Yuji Itadori menelan kutukan tingkat tinggi Ryomen Sukuna untuk menyelamatkan temannya, menjadikannya wadah raja kutukan dan membawanya ke dunia Penyihir Jujutsu.',
    cover_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    author: 'Gege Akutami',
    status: 'completed',
    rating: 4.90,
    source_id: 'src-1',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    genres: [MOCK_GENRES[0], MOCK_GENRES[9]], // Action, Supernatural
    latest_chapter: {
      id: 'ch-501',
      chapter_number: 271,
      title: 'Perpisahan dan Harapan',
      released_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    },
  },
  {
    id: 'c-6',
    slug: 'tales-of-demons-and-gods',
    title: 'Tales of Demons and Gods',
    alt_titles: ['Yao Shen Ji'],
    type: 'manhua',
    synopsis: 'Nie Li, Spiritualis Demon terkuat di kehidupan sebelumnya, terlahir kembali ke masa lalunya ketika berusia 13 tahun dengan ingatan masa depan untuk menyelamatkan kotanya.',
    cover_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    author: 'Mad Snail',
    status: 'ongoing',
    rating: 4.75,
    source_id: 'src-2',
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    genres: [MOCK_GENRES[2], MOCK_GENRES[5], MOCK_GENRES[6]], // Fantasy, Martial Arts, Isekai
    latest_chapter: {
      id: 'ch-601',
      chapter_number: 480.5,
      title: 'Ranah Spiritualis Dewa',
      released_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
  },
];

export const MOCK_CHAPTERS: Record<string, Chapter[]> = {
  'solo-leveling': [
    {
      id: 'ch-101',
      comic_id: 'c-1',
      chapter_number: 179,
      title: 'Kebangkitan Sang Shadow Monarch',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 5 * 60000).toISOString(),
      created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    },
    {
      id: 'ch-102',
      comic_id: 'c-1',
      chapter_number: 178,
      title: 'Pertempuran Terakhir di Seoul',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 24 * 3600000).toISOString(),
      created_at: new Date(Date.now() - 25 * 3600000).toISOString(),
    },
    {
      id: 'ch-103',
      comic_id: 'c-1',
      chapter_number: 177,
      title: 'Pasukan Kegelapan Berkumpul',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 48 * 3600000).toISOString(),
      created_at: new Date(Date.now() - 49 * 3600000).toISOString(),
    },
    {
      id: 'ch-104',
      comic_id: 'c-1',
      chapter_number: 1,
      title: 'Pemburu Terlemah Kelas E',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 365 * 86400000).toISOString(),
      created_at: new Date(Date.now() - 365 * 86400000).toISOString(),
    },
  ],
  'one-piece': [
    {
      id: 'ch-201',
      comic_id: 'c-2',
      chapter_number: 1115,
      title: 'Dunia yang Tenggelam',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 12 * 60000).toISOString(),
      created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    },
    {
      id: 'ch-202',
      comic_id: 'c-2',
      chapter_number: 1114,
      title: 'Pesan Vegapunk Kepada Dunia',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 7 * 86400000).toISOString(),
      created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
  ],
  'martial-peak': [
    {
      id: 'ch-301',
      comic_id: 'c-3',
      chapter_number: 3520,
      title: 'Terobosan Ranah Kaisar',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 30 * 60000).toISOString(),
      created_at: new Date(Date.now() - 35 * 60000).toISOString(),
    },
  ],
  'tower-of-god': [
    {
      id: 'ch-401',
      comic_id: 'c-4',
      chapter_number: 600,
      title: 'Kebenaran di Lantai 135',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 2 * 3600000).toISOString(),
      created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
  ],
  'jujutsu-kaisen': [
    {
      id: 'ch-501',
      comic_id: 'c-5',
      chapter_number: 271,
      title: 'Perpisahan dan Harapan',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 24 * 3600000).toISOString(),
      created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    },
  ],
  'tales-of-demons-and-gods': [
    {
      id: 'ch-601',
      comic_id: 'c-6',
      chapter_number: 480.5,
      title: 'Ranah Spiritualis Dewa',
      status: 'published',
      retry_count: 0,
      released_at: new Date(Date.now() - 5 * 3600000).toISOString(),
      created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
  ],
};

export const MOCK_PAGES: Record<string, ChapterPage[]> = {
  'ch-101': [
    { id: 'p-1', chapter_id: 'ch-101', page_number: 1, image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
    { id: 'p-2', chapter_id: 'ch-101', page_number: 2, image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
    { id: 'p-3', chapter_id: 'ch-101', page_number: 3, image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
    { id: 'p-4', chapter_id: 'ch-101', page_number: 4, image_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
    { id: 'p-5', chapter_id: 'ch-101', page_number: 5, image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
  ],
  'ch-201': [
    { id: 'p-21', chapter_id: 'ch-201', page_number: 1, image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
    { id: 'p-22', chapter_id: 'ch-201', page_number: 2, image_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
    { id: 'p-23', chapter_id: 'ch-201', page_number: 3, image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80', width: 800, height: 1200 },
  ],
};

export const MOCK_INGEST_QUEUE = [
  {
    id: 'ch-queued-1',
    chapter_title: 'Solo Leveling Ch. 180 (Draft)',
    comic_title: 'Solo Leveling',
    status: 'processing' as const,
    progress_pages: 8,
    total_pages: 20,
    retry_count: 0,
    updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: 'ch-queued-2',
    chapter_title: 'Martial Peak Ch. 3521',
    comic_title: 'Martial Peak',
    status: 'pending' as const,
    progress_pages: 0,
    total_pages: 15,
    retry_count: 0,
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'ch-queued-3',
    chapter_title: 'Tales of Demons Ch. 481',
    comic_title: 'Tales of Demons and Gods',
    status: 'failed' as const,
    progress_pages: 3,
    total_pages: 18,
    retry_count: 2,
    updated_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
];

export const MOCK_INGEST_LOGS: IngestLog[] = [
  {
    id: 'log-1',
    source_id: 'src-1',
    chapter_id: 'ch-queued-3',
    level: 'error',
    message: 'HTTP 403 Forbidden when fetching image page 4 from source URL',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'log-2',
    source_id: 'src-1',
    chapter_id: 'ch-101',
    level: 'info',
    message: 'Successfully ingested Chapter 179 for Solo Leveling (5 pages converted to WebP)',
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'log-3',
    source_id: 'src-2',
    chapter_id: 'ch-201',
    level: 'info',
    message: 'Ingested Chapter 1115 for One Piece, uploaded to Cloudflare R2 CDN',
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
];
